### ISSUE TITLE
When running your code I got a error

### ISSUE THREAD

**Issue by usalexsantos** [callmesusheel/image-background-removal#2]
Hi @susheelsk, I got an error running your code.

C:\image-background>python seg.py /input/0001.jpg /output/0001.png 1
Traceback (most recent call last):
  File "seg.py", line 89, in <module>
    MODEL = DeepLabModel(modelType)
  File "seg.py", line 25, in __init__
    graph_def = tf.GraphDef.FromString(open(tarball_path + "/frozen_inference_graph.pb", "rb").read())
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

Can you help?

**Comment by susheelsk** [comment]
Looks like a virtualenv issue. Can you try reinstalling tf?

**Comment by dirkk0** [comment]
`pip3 install tensorflow==1.14` fixes this.

**Comment by NMNaufaldo** [comment]
@dirkk0 In my case, I've to downgrade Python 3.8 to 3.7 to be able to install tensorflow==1.14

**Comment by dome272** [comment]
For those that might have the same issue and dont want to downgrade anything I found this solution:
[https://github.com/tensorflow/models/issues/7703#issuecomment-545669265](https://github.com/tensorflow/models/issues/7703#issuecomment-545669265)

**Comment by SaeedArisha** [comment]
instead of downgrading the Tf version trace the error, go to the line causing it, and then write tf.compat.v1.GraphDef

**Comment by adills** [comment]
Needed to make the following 3 changes in the seg.py file to be compatible with Py 3.11.6, tf 2.16.1, and pillow 10.2.0:

1. line 25, tf.GraphDef.FromString tf.compat.v1.GraphDef.FromString
2. line 33, tf.Session to tf.compat.v1.Session
3. line 50, Image.ANTIALIAS to Image.LANCZOS

See updated file attached.  Change the .txt back to .py after downloading.
[seg.txt](https://github.com/susheelsk/image-background-removal/files/14817201/seg.txt)
